### PR TITLE
one more time fixing CLI flags refactor

### LINKED ISSUE #1333: "zq -version" broke at commit 7f00817
WIth the arrival of commit `7f00817` that corresponds to PR #1323, `zq -version` stopped working. It just prints the help text now.

```
$ zq -version
NAME
    zq - command line logs processor

USAGE
    zq [ options ] [ zql ] file [ file ... ]
...
```

### PR DESCRIPTION
**Pull request by mccanne**
The last refactor broke "zq -version".  The previous logic was a bit
fragile because cli.Flags.Init() would return a flag to stop
executing if -version was given.  But now, Init() can fail for
other reasons, e.g., writing binary data to stdout.  This would
block the help screen if Init was before the help check, but if we
put it after, then help would be displayed with -version.

The fix is to simplify the logic by cli.Init calling os.Exit if
"-version" is given and putting the error check after the subsequent
check for help.  This only applies to zq and not the other tools
because the other tools use subcommands and the issue does not
arise with the root command that does not have outputFlags checks.

We also added procFlags to zqd since they were missing in the last
refactor.  This gives "-sortmem" back to zqd.

Fixes #1333

### CODE REVIEW

File: cmd/microindex/root/command.go [hunk 1]
```diff
@@ -41,11 +41,12 @@ func New(parent charm.Command, f *flag.FlagSet) (charm.Command, error) {
...
 func (c *Command) Run(args []string) error {
 	defer c.cli.Cleanup()
-	if ok, err := c.cli.Init(); !ok {
-		return err
-	}
+	err := c.cli.Init()
 	if len(args) == 0 {
 		return MicroIndex.Exec(c, []string{"help"})
 	}
+	if err != nil {
```
Comment (mattnibs) [inline cmd/microindex/root/command.go:48]: drop line 44 and do
```suggestion
	if err := c.cli.Init(); err != nil {
```

**Review by mattnibs — APPROVED** [review]

**Comment by alfred-landrum** [comment]
Can you add a test for the `zq -version` call?

File: cmd/microindex/root/command.go (hunk 1 above)
Comment (mccanne) [reply cmd/microindex/root/command.go:48]: If you do this, then you'll get the help screen when you run `microindex -version`.

Comment (mccanne) [reply cmd/microindex/root/command.go:48]: It's a little fragile.  I think I'll leave it as is until we come up with something better.
