### PR TITLE
fix bug with parents slice corruption in compiler

### LINKED ISSUE #1635: stack overflow with merge proc
In compiler.go, compileSequential calls `merge.New()` with a slice of proc.Interfaces, which `merge.New` does *not* copy, it just retains the slice. compileSequential later rearranges the slice such that the merge proc has a parent pointer to itself, eventually leading to a stack overflow.

### PR DESCRIPTION
**Pull request by mccanne**
This commit fixes a bug where the parents slice was overwritten
and reused so the parent linkage in the compiled flowgraph
becomes corrupt.  The fix is to make a new parents slice instead
of trying to reuse the buffer.

Fixes #1635

### CODE REVIEW

File: proc/compiler/compiler_test.go [hunk 1]
```diff
@@ -67,3 +68,39 @@ func TestCompileParents(t *testing.T) {
...
+0:[1;]
+0:[2;]
+0:[3;]
+0:[4;]
+`
+	zctx := resolver.NewContext()
+	pctx := &proc.Context{Context: context.Background(), TypeContext: zctx}
+	r := tzngio.NewReader(bytes.NewReader([]byte(input)), zctx)
+	src := &proctest.RecordPuller{R: r}
+	t.Run("merge done before scanners out of data", func(t *testing.T) {
```
Comment (alfred-landrum) [inline proc/compiler/compiler_test.go:88]: I suggest removing the t.Run wrapper, and call the inner code directly.

**Review by alfred-landrum — APPROVED** [review]
I tested this change with the same setup where I discovered it, and this fixes the stack overflow.
