### PR TITLE
Use proc.ColumnBuilder in zio/ndjsonio.inferParser

### LINKED ISSUE #747: Inferred json reader crashes on multiple nested fields
I noticed this while working on #714.

```
$ echo '{"a.b.c": 1, "a.b.d": 2}' | zq -t -
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/brimsec/zq/zio/ndjsonio.(*inferParser).parseObject(0xc000032608, 0xc000342000, 0x18, 0x10000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3, ...)
        /Users/henridf/work/brim/zq/zio/ndjsonio/inferparser.go:62 +0xe2c
github.com/brimsec/zq/zio/ndjsonio.(*Reader).Parse(0xc000032600, 0xc000342000, 0x18, 0x10000, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00003c090, ...)
        /Users/henridf/work/brim/zq/zio/ndjsonio/reader.go:112 +0x184
github.com/brimsec/zq/zio/ndjsonio.(*Reader).Read(0xc000032600, 0x13d9f42, 0x18f8ce0, 0xc00003c090)
        /Users/henridf/work/brim/zq/zio/ndjsonio/reader.go:126 +0xac
github.com/brimsec/zq/zio/detector.match(0x1b903c0, 0xc000032600, 0x195f8a4, 0x6, 0x0, 0x0)
        /Users/henridf/work/brim/zq/zio/detector/reader.go:70 +0x38
github.com/brimsec/zq/zio/detector.NewReader(0x1b90340, 0xc0002fb200, 0xc0002e2540, 0xc0002fb200, 0xc0000be000, 0x0, 0x1)
        /Users/henridf/work/brim/zq/zio/detector/reader.go:49 +0x588
github.com/brimsec/zq/zio/detector.OpenFromNamedReadCloser(0xc0002e2540, 0x1b99b20, 0xc0000be000, 0x7ffeefbffa86, 0x1, 0x195d3d9, 0x4, 0x1, 0x0, 0x1998ef3, ...)
        /Users/henridf/work/brim/zq/zio/detector/file.go:131 +0xaf
github.com/brimsec/zq/zio/detector.OpenFile(0xc0002e2540, 0x7ffeefbffa86, 0x1, 0x195d3d9, 0x4, 0x1, 0x0, 0x1998ef3, 0x59, 0x0, ...)
        /Users/henridf/work/brim/zq/zio/detector/file.go:68 +0x11a
main.(*Command).inputReaders(0xc0002e40a0, 0xc0000ce050, 0x1, 0x1, 0x0, 0x0, 0xaa00000001927a60, 0x1115f01, 0xaa7e7729fbbf34ca)
        /Users/henridf/work/brim/zq/cmd/zq/zq.go:270 +0x166
main.(*Command).Run(0xc0002e40a0, 0xc0000ce050, 0x1, 0x1, 0x0, 0x0)
        /Users/henridf/work/brim/zq/cmd/zq/zq.go:218 +0x2cf
github.com/mccanne/charm.(*instance).run(0xc0000ede20, 0xc0000ce040, 0x2, 0x2, 0x0, 0x0)
        /Users/henridf/go/pkg/mod/github.com/mccanne/charm@v0.0.3-0.20191224190439-b05e1b7b1be3/instance.go:53 +0x28c
github.com/mccanne/charm.(*Spec).ExecRoot(0x2155000, 0xc0000ce040, 0x2, 0x2, 0xc0002cdf50, 0x100742f, 0xc0000a6058, 0x0)
        /Users/henridf/go/pkg/mod/github.com/mccanne/charm@v0.0.3-0.20191224190439-b05e1b7b1be3/charm.go:77 +0x96
main.main()
        /Users/henridf/work/brim/zq/cmd/zq/main.go:9 +0x78
```

### PR DESCRIPTION
**Pull request by nwt**
A zio/ndjsonio.Reader without type configuration produces incorrect output for '{"a.b.c":1}' and panics on '{"a.b.c":1,"a.b.d":2}'. Fix by using proc.ColumnBuilder in zio/ndjsonio.(*inferParser).parseObject.

Closes #747.

This allocates a new ColumnBuilder on every successful trip through parseObject. That isn't great, but effective reuse doesn't seem trivial since there's no guarantee the next record will have the same fields, so I'm kicking that can down the road.

### CODE REVIEW

File: zio/ndjsonio/inferparser.go [hunk 1]
```diff
@@ -36,56 +36,34 @@ func (p *inferParser) parseObject(b []byte) (zng.Value, error) {
...
+		return zng.Value{}, err
+	}
+	for _, v := range zngValues {
+		columnBuilder.Append(v.Bytes, zng.IsContainerType(zng.AliasedType(v.Type)))
+	}
+	bytes_, err := columnBuilder.Encode()
+	if err != nil {
+		return zng.Value{}, err
+	}
+	return zng.Value{Type: typ, Bytes: bytes_}, nil
```
Comment (alfred-landrum) [inline zio/ndjsonio/inferparser.go:66]: nit: suggest a var name that doesn't end in `_`

```suggestion
	b, err := columnBuilder.Encode()
	if err != nil {
		return zng.Value{}, err
	}
	return zng.Value{Type: typ, Bytes: b}, nil
```

Comment (nwt) [reply zio/ndjsonio/inferparser.go:66]: We don’t have a great conventional name for a zcode.Bytes variables like this one. How about zbytes?

Comment (alfred-landrum) [reply zio/ndjsonio/inferparser.go:66]: sure, `zbytes` sounds good

Comment (nwt) [reply zio/ndjsonio/inferparser.go]: Done in https://github.com/brimsec/zq/pull/948/commits/511f8b753b6c314708f9c5811a79e2987a17339e.
