### PR TITLE
Fix single remaining case of string api error response

### LINKED ISSUE #496: HTTP errors should return json payloads
For zqd, if an error ours on a request the response should always be a json response.

### PR DESCRIPTION
**Pull request by henridf**
closes #496

### CODE REVIEW

File: zqd/api/api.go [hunk 1]
```diff
@@ -13,9 +13,10 @@ import (
 )
 
 type Error struct {
-	Type    string      `json:"type"`
-	Message string      `json:"error"`
-	Info    interface{} `json:"info,omitempty"`
+	Type      string      `json:"type"`
+	ErrorType string      `json:"error_type"`
```
Comment (alfred-landrum) [inline zqd/api/api.go:17]: This could be useful, but I don't see it utilized in the PR?

Comment (henridf) [reply zqd/api/api.go:17]: ooops... that's an omission that i've fixed in a follow-on commit. the purpose of this field is to hold the "Kind" string which was previously being written into Type. (This field could also be called Kind instead of ErrorType btw... happy to change if any strong preference).

Comment (alfred-landrum) [reply zqd/api/api.go:17]: Ok! My naming preference is `Kind`, then.
