### PR TITLE
Fix seekindex lookups for descending order indices

### LINKED ISSUE #1579: zar import missing records
Using the ~4GB `wrccdc-year1` logs, I see a large discrepancy in records when I import it into zar:

```
$ zq -t "count()" ~/work/data/wrccdc-year1/zeek-logs-sort-r-ts.zng
#0:record[count:uint64]
0:[96217189;]
...
$ zar import -s 128MiB ~/work/data/wrccdc-year1/zeek-logs-sort-r-ts.zng
...
$ zar zq -t "count()"
#0:record[count:uint64]
0:[94839372;]
```

Additionally, if I try to manually verify against the data files in the resulting archive, I see this zq error:
```
$ find zarroot -name "d*.zng" | xargs zq -t "count()"
zarroot/zd/20170324/d-1k4BMtV8RQt4HzJxdVMFhkJv3DA.zng: _path (string): expected primitive type, got container
```

I wonder if this is related to the fact that some records have the same timestamp, as I saw a similar problem when I was working on the overlap support. (Though note the above runs don't perform any compaction).

### PR DESCRIPTION
**Pull request by mattnibs**
Fix an off-by-one error one descending seek indexes that was causing missed
records in certain circumstances.

Additionally: The way the seek index was written, made it difficult to isolate
issues. As such I moved seekindex into its own package that includes both
builder and reader functionality.

Closes #1579

### CODE REVIEW

File: ppl/archive/import.go [hunk 1]
```diff
@@ -377,38 +359,17 @@ func (cw *chunkWriter) closeWithTs(ctx context.Context, firstTs, lastTs nano.Ts)
...
-		microindex.FrameThresh(framesize),
-		microindex.Order(cw.ark.DataOrder),
-	)
-	if err != nil {
-		return Chunk{}, err
-	}
-	if err = zbuf.CopyWithContext(ctx, idxWriter, tfr); err != nil {
-		idxWriter.Abort()
+	if err := cw.seekIndex.Close(); err != nil {
+		cw.seekIndex.Abort()
```
Comment (alfred-landrum) [inline ppl/archive/import.go:366]: I see that the reason to call an Abort after a failed Close is that it will try to remove the partially written index file in Abort(), which we would want to do, otherwise we need to add logic to ignore a failed index read (since a partially written index file could cause reads of its data file to fail).

For simplicity sake, how about moving the close error check & Abort call inside the index builder's Close call?

This makes me think that microindex.Writer should use an iosrc.Replacer instead of an iosrc.Writer, so that the index writer can call replacer.Abort() - on S3, that will cancel the multipart upload & ensure that there's no partially written index file.

File: ppl/archive/seekindex/builder.go [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+	"github.com/brimsec/zq/microindex"
+	"github.com/brimsec/zq/pkg/nano"
+	"github.com/brimsec/zq/zbuf"
+	"github.com/brimsec/zq/zng"
+	"github.com/brimsec/zq/zng/resolver"
+)
+
+type Builder struct {
+	builder *zng.Builder
+	path    string
```
Comment (alfred-landrum) [inline ppl/archive/seekindex/builder.go:15]: I don't see path used anywhere?

File: ppl/archive/seekindex/seekindex_test.go [hunk 3]
```diff
@@ -0,0 +1,103 @@
...
+	"github.com/brimsec/zq/pkg/iosrc"
+	"github.com/brimsec/zq/pkg/nano"
+	"github.com/brimsec/zq/zbuf"
+	"github.com/stretchr/testify/assert"
+	"github.com/stretchr/testify/require"
+)
+
+func TestAscending(t *testing.T) {
+	var entries = []entry{
+		{1490469784771872000, 0},
```
Comment (alfred-landrum) [inline ppl/archive/seekindex/seekindex_test.go:20]: Would you change the timestamps here so that they're easier to read at a glance, as in TestDescending?

File: ppl/archive/seekindex/seekindex_test.go [hunk 4]
```diff
@@ -0,0 +1,103 @@
...
+
+func (t *testSeekIndex) Lookup(span nano.Span, expected Range) {
+	rg, err := t.SeekIndex.Lookup(context.Background(), span)
+	require.NoError(t, err)
+	assert.Equal(t, expected, rg)
+}
+
+func newTestSeekIndex(t *testing.T, entries []entry) *testSeekIndex {
+	path := build(t, entries)
+	s, err := Open(context.Background(), iosrc.MustParseURI(path))
```
Comment (alfred-landrum) [inline ppl/archive/seekindex/seekindex_test.go:85]: I don't see a paired Close() for this open call.

File: ppl/archive/seekindex/builder.go (hunk 2 above)
Comment (mattnibs) [reply ppl/archive/seekindex/builder.go:15]: Nope, removing it.

File: ppl/archive/import.go (hunk 1 above)
Comment (mattnibs) [reply ppl/archive/import.go:366]: Sure

File: ppl/archive/seekindex/seekindex_test.go [hunk 5]
```diff
@@ -0,0 +1,104 @@
...
+		{500, 904528},
+		{400, 1139588},
+		{300, 1355498},
+		{200, 1564211},
+		{100, 1776965},
+	}
+	s := newTestSeekIndex(t, entries)
+	s.Lookup(nano.Span{Ts: 900, Dur: 1}, Range{0, 215367})
+	s.Lookup(nano.Span{Ts: 700, Dur: 1}, Range{438514, 680477})
+	s.Lookup(nano.Span{Ts: 750, Dur: 100}, Range{0, 438514})
```
Comment (alfred-landrum) [inline ppl/archive/seekindex/seekindex_test.go:53]: Why isn't this `Range(215367, 438514)`?

File: ppl/archive/import.go [hunk 6]
```diff
@@ -264,20 +261,18 @@ func (dw *tsDirWriter) flush() error {
...
-	needIndexWrite  bool
-	tsd             tsDir
-	wroteFirst      bool
+	ark            *Archive
+	byteCounter    *writeCounter
+	count          uint64
+	dataFileWriter *zngio.Writer
+	firstTs        nano.Ts
+	id             ksuid.KSUID
+	seekIndex      *seekindex.Builder
```
Comment (nwt) [inline ppl/archive/import.go:270]: Nit: Put this between needIndexWrite and tsd (and likewise in newChunkWriter).

**Review by alfred-landrum — APPROVED** [review]

File: ppl/archive/seekindex/builder.go [hunk 7]
```diff
@@ -0,0 +1,48 @@
...
+
+func NewBuilder(ctx context.Context, path string, order zbuf.Order) (*Builder, error) {
+	zctx := resolver.NewContext()
+	writer, err := microindex.NewWriterWithContext(ctx, zctx, path, microindex.Order(order), microindex.Keys("ts"))
+	if err != nil {
+		return nil, err
+	}
+	builder := zng.NewBuilder(zctx.MustLookupTypeRecord(Schema))
+	return &Builder{
+		builder: builder,
```
Comment (nwt) [inline ppl/archive/seekindex/builder.go:26]:
```suggestion
	return &Builder{
		builder: zng.NewBuilder(zctx.MustLookupTypeRecord(Schema)),
```

File: ppl/archive/seekindex/builder.go [hunk 8]
```diff
@@ -0,0 +1,48 @@
...
+	rec := b.builder.Build(zng.EncodeTime(ts), zng.EncodeInt(offset))
+	return b.writer.Write(rec)
+}
+
+func (b *Builder) Abort() error {
+	return b.writer.Abort()
+}
+
+// Close closes the underlying microindex.Writer. Should an error occur the
+// microindex will be deleted via a call to abort.
```
Comment (nwt) [inline ppl/archive/seekindex/builder.go:41]:
```suggestion
// microindex will be deleted via a call to Abort.
```

File: ppl/archive/seekindex/seekindex.go [hunk 9]
```diff
@@ -0,0 +1,88 @@
...
+
+	"github.com/brimsec/zq/microindex"
+	"github.com/brimsec/zq/pkg/iosrc"
+	"github.com/brimsec/zq/pkg/nano"
+	"github.com/brimsec/zq/zbuf"
+	"github.com/brimsec/zq/zng"
+	"github.com/brimsec/zq/zng/resolver"
+)
+
+var Schema = []zng.Column{
```
Comment (nwt) [inline ppl/archive/seekindex/seekindex.go:15]: Maybe declare this in builder.go since that's where it's used? And maybe make it private?

**Review by nwt — APPROVED** [review]

File: ppl/archive/seekindex/seekindex.go (hunk 9 above)
Comment (mattnibs) [reply ppl/archive/seekindex/seekindex.go:15]: Sure
