### PR TITLE
make fuse stable

### LINKED ISSUE #1702: Non-deterministic "fuse" behavior
Should `fuse` behave in a deterministic manner? I've noticed that one of the `fuse` docs examples I previously created fails the automated tests occasionally because its output sometimes flips.

Using the [Zeek TSV zq-sample-data](https://github.com/brimsec/zq-sample-data/tree/master/zeek-default), as of `zq` commit `0759cc38` this base output seems to be generated deterministically:

```
$ zq -t 'ts < 1521911721' stats.log.gz weird.log.gz
#0:record[_path:string,ts:time,peer:bstring,mem:uint64,pkts_proc:uint64,bytes_recv:uint64,pkts_dropped:uint64,pkts_link:uint64,pkt_lag:duration,events_proc:uint64,events_queued:uint64,active_tcp_conns:uint64,active_udp_conns:uint64,active_icmp_conns:uint64,tcp_conns:uint64,udp_conns:uint64,icmp_conns:uint64,timers:uint64,active_timers:uint64,files:uint64,active_files:uint64,dns_requests:uint64,active_dns_requests:uint64,reassem_tcp_size:uint64,reassem_file_size:uint64,reassem_frag_size:uint64,reassem_unknown_size:uint64]
0:[stats;1521911720.600725;zeek;74;26;29375;-;-;-;404;11;1;0;0;1;0;0;36;32;0;0;0;0;1528;0;0;0;]
#port=uint16
#1:record[_path:string,ts:time,uid:bstring,id:record[orig_h:ip,orig_p:port,resp_h:ip,resp_p:port],name:bstring,addl:bstring,notice:bool,peer:bstring]
1:[weird;1521911720.600843;C1zOivgBT6dBmknqk;[10.47.1.152;49562;23.217.103.245;80;]TCP_ack_underflow_or_misorder;-;F;zeek;]
1:[weird;1521911720.608108;-;[-;-;-;-;]truncated_header;-;F;zeek;]
1:[weird;1521911720.610033;C45Ff03lESjMQQQej1;[10.47.5.155;40712;91.189.91.23;80;]above_hole_data_without_any_acks;-;F;zeek;]
1:[weird;1521911720.742818;Cs7J9j2xFQcazrg7Nc;[10.47.8.100;5900;10.129.53.65;58485;]connection_originator_SYN_ack;-;F;zeek;]
```

However, if I `fuse` it and turn it into CSV output, sometimes the first unique columns are the ones associated with the `weird` events:

```
$ zq -f csv 'ts < 1521911721 | fuse' stats.log.gz weird.log.gz
_path,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,name,addl,notice,peer,mem,pkts_proc,bytes_recv,pkts_dropped,pkts_link,pkt_lag,events_proc,events_queued,active_tcp_conns,active_udp_conns,active_icmp_conns,tcp_conns,udp_conns,icmp_conns,timers,active_timers,files,active_files,dns_requests,active_dns_requests,reassem_tcp_size,reassem_file_size,reassem_frag_size,reassem_unknown_size
stats,2018-03-24T17:15:20.600725Z,-,-,-,-,-,-,-,-,zeek,74,26,29375,-,-,-,404,11,1,0,0,1,0,0,36,32,0,0,0,0,1528,0,0,0
weird,2018-03-24T17:15:20.600843Z,C1zOivgBT6dBmknqk,10.47.1.152,49562,23.217.103.245,80,TCP_ack_underflow_or_misorder,-,F,zeek,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
weird,2018-03-24T17:15:20.608108Z,-,-,-,-,-,truncated_header,-,F,zeek,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
weird,2018-03-24T17:15:20.610033Z,C45Ff03lESjMQQQej1,10.47.5.155,40712,91.189.91.23,80,above_hole_data_without_any_acks,-,F,zeek,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
weird,2018-03-24T17:15:20.742818Z,Cs7J9j2xFQcazrg7Nc,10.47.8.100,5900,10.129.53.65,58485,connection_originator_SYN_ack,-,F,zeek,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
```

Then sometimes (less frequently, it seems) the first unique columns are the ones associated with the `stats` event:

```
$ zq -f csv 'ts < 1521911721 | fuse' stats.log.gz weird.log.gz
_path,ts,peer,mem,pkts_proc,bytes_recv,pkts_dropped,pkts_link,pkt_lag,events_proc,events_queued,active_tcp_conns,active_udp_conns,active_icmp_conns,tcp_conns,udp_conns,icmp_conns,timers,active_timers,files,active_files,dns_requests,active_dns_requests,reassem_tcp_size,reassem_file_size,reassem_frag_size,reassem_unknown_size,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,name,addl,notice
stats,2018-03-24T17:15:20.600725Z,zeek,74,26,29375,-,-,-,404,11,1,0,0,1,0,0,36,32,0,0,0,0,1528,0,0,0,-,-,-,-,-,-,-,-
weird,2018-03-24T17:15:20.600843Z,zeek,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,C1zOivgBT6dBmknqk,10.47.1.152,49562,23.217.103.245,80,TCP_ack_underflow_or_misorder,-,F
weird,2018-03-24T17:15:20.608108Z,zeek,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,truncated_header,-,F
weird,2018-03-24T17:15:20.610033Z,zeek,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,C45Ff03lESjMQQQej1,10.47.5.155,40712,91.189.91.23,80,above_hole_data_without_any_acks,-,F
weird,2018-03-24T17:15:20.742818Z,zeek,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,Cs7J9j2xFQcazrg7Nc,10.47.8.100,5900,10.129.53.65,58485,connection_originator_SYN_ack,-,F
```

### PR DESCRIPTION
**Pull request by mccanne**
This commit changes the fuser so the output type columns of
the union schema are stable.  Previously, the column order
was dependent on the type IDs, which could be non-deterministic
when scanning parallel inputs.  The new code determines the
column order from the order of the types encountered in the
incoming stream.

This fix will address intermittent CI failures due to this indeterminacy.

Fixes #1702

### CODE REVIEW

File: proc/fuse/fuser.go [hunk 1]
```diff
@@ -83,19 +85,18 @@ func (f *Fuser) stash(rec *zng.Record) error {
...
 
 func (f *Fuser) finished() bool {
-	return f.slotByID != nil
+	return f.typeSlots != nil
 }
 
 func (f *Fuser) finish() error {
 	uber := newSchema()
-	// slotByID provides a map from a type ID to a slice of integers
+	// typeSlots provides a map from a type ID to a slice of integers
```
Comment (henridf) [inline proc/fuse/fuser.go:93]:
```suggestion
	// typeSlots provides a map from a type to a slice of integers
```

**Review by henridf — APPROVED** [review]

**Review by nwt — APPROVED** [review]
