### PR TITLE
Simplify zar zq

### LINKED ISSUE #757: Factor out common option handling between zq and zar zq
`zq` and `zar zq` share a number of command-line options. Currently, the related handling code is duplicated. We should unify this. As a code/refactor task this should be straightforward, but this task has the prerequisite of settling "what options should `zar zq` support" first.

### LINKED ISSUE #759: Cleaner `zar zq` output on stdout with text formats
The zar README brings the reader to this `zar zq` query:

```sh
$ zar zq "count()" _ | zq -f table -
COUNT
222617
223815
218575
...
```

at which point, one might recall that zar zq supportsd different output formats, and directly try:

```sh
$ zar zq -f table "count()" _ 
COUNT
222617
COUNT
223815
COUNT
218575
...
```

which gives correct results, but with extra headers that are a little surprising. This is not a bug, but would likely be unexpected to someone without deep familiarity with the inner workings of zq and zar (as a README reader might be).

This can be addressed as suggested by @mccanne:

> A fix could be for stdout to merge the zng sub-streams that are created during the walk into one type context  and have a single writer instance for stdout.

### PR DESCRIPTION
**Pull request by henridf**
This PR has two simplifying changes to `zar zq`. The change itself is straightforward but has implications on zar in two ways:

- The first commit removes the `-f` flag, such that `zar zq` always emits zng. This is the way it is used throughout the README, and for other formats, one can pipe `zar zq` into `zq`, as in the README.  (And as it says, "we love pipes"!). This closes #759.

- The second commit removes all input reader flags. Given that zar archive contents are stored in zng, there's no need for json-related flags.  This closes #757.

### CODE REVIEW

File: cmd/zar/zq/command.go [hunk 1]
```diff
@@ -224,7 +179,8 @@ func (c *Command) openOutput(zardir, filename string) (zbuf.WriteCloser, error)
 	if path != "" {
 		path = filepath.Join(zardir, filename)
 	}
-	w, err := emitter.NewFile(path, &c.WriterFlags)
+	flags := zio.WriterFlags{Format: "zng"}
+	w, err := emitter.NewFile(path, &flags)
```
Comment (nwt) [inline cmd/zar/zq/command.go:183]:
```suggestion
	w, err := emitter.NewFile(path, &zio.WriterFlags{Format: "zng"})
```
