### PR TITLE
Init apiserver.Manager only when needed

### LINKED ISSUE #1935: zqd: Recruiter/Workers should not initialize apiserver.Manager
As observed while @marktwallace was testing helm postgres draft pr #1917, recruiter and worker containers fail to initialize if they do not have access to the postgres database. They should not have access to the postgres database.

Have zqd instances with the recruiter and worker personalities not initialize the space manager which needs access to postgres (if db.kind is set to postgres).

### PR DESCRIPTION
**Pull request by mattnibs**
No reason to init apiserver.Manager when the personalities worker and recruiter
have no use for them. Only init apiserver.Manager for personalities that serve
the api server routes.

Closes #1935

### CODE REVIEW

File: ppl/zqd/core.go [hunk 1]
```diff
@@ -147,7 +140,14 @@ func NewCore(ctx context.Context, conf Config) (*Core, error) {
...
 }
 
-func (c *Core) addAPIServerRoutes() {
+func (c *Core) addAPIServerRoutes(ctx context.Context, conf Config) (err error) {
+	c.root, err = iosrc.ParseURI(conf.Root)
+	if err != nil {
+		return
+	}
+	if c.mgr, err = apiserver.NewManager(ctx, conf.Logger, c.registry, c.root, conf.DB); err != nil {
+		return
```
Comment (nwt) [inline ppl/zqd/core.go:149]: Nit: I think adorned returns improve readability.

**Review by nwt — APPROVED** [review]

File: ppl/zqd/core.go (hunk 1 above)
Comment (mattnibs) [reply ppl/zqd/core.go:149]: I can get behind this.
