### PR TITLE
fix scanning of zson primitives

### LINKED ISSUE #2056: ZSON input: mismatched braces while parsing record type (redux)
Repro is with `zq` commit `d45eae4` using the [zq-sample-data](https://github.com/brimsec/zq-sample-data) in the `zng/` directory. This can be reproduced with many of the ZNG logs found there, but for ease of study I'm starting with the smallest one.

```
zq-sample-data/zng$ zq -f zson 'head 608' ntp.zng.gz | zq -t -i zson -
...
3;]4;3;0;1;1;0;0;\x00\x00\x00\x00;0;0;0;1521912411.191308;0;]
0:[ntp;1521912423.775761;CagU2T3HdhhP1dJ07f;[10.47.6.50;46163;85.199.214.102;123;]4;3;0;1;1;0;0;\x00\x00\x00\x00;0;0;0;1521912411.191308;0;]
/dev/stdin: parse error: mismatched braces while parsing record type
```

If Iower that to `head 607`, the problem is not triggered. If I isolate just the ZSON output data that came after that last successful record (spotted by `uid`), I don't see an obvious culprit as to what's triggering the parse problem (recall we saw this same error in #1966 where the root cause was an unexpected "mu" character).

```
zq-sample-data/zng$ zq -f zson 'head 608' ntp.zng.gz
...
{
    _path: "ntp",
    ts: 2018-03-24T17:27:03.775761Z,
    uid: "CagU2T3HdhhP1dJ07f",
    id: {
        orig_h: 10.47.6.50,
        orig_p: 46163,
        resp_h: 85.199.214.102,
        resp_p: 123
    },
    version: 4,
    mode: 3,
    stratum: 0,
    poll: 1s,
    precision: 1s,
    root_delay: 0s,
    root_disp: 0s,
    ref_id: "\x00\x00\x00\x00",
    ref_time: 1970-01-01T00:00:00Z,
    org_time: 1970-01-01T00:00:00Z,
    rec_time: 1970-01-01T00:00:00Z,
    xmt_time: 2018-03-24T17:26:51.191308Z,
    num_exts: 0
} (1)
{
    _path: "ntp",
    ts: 2018-03-24T17:27:04.163338Z,
    uid: "CiWD2E4B4MdjDfbRJf",
    id: {
        orig_h: 10.47.4.100,
        orig_p: 123,
        resp_h: 162.210.111.4,
        resp_p: 123
    },
    version: 4,
    mode: 3,
    stratum: 2,
    poll: 17m4s,
    precision: 0s,
    root_delay: 155.029ms,
    root_disp: 340.332ms,
    ref_id: "131.188.3.221",
    ref_time: 2018-03-24T01:46:11.275708Z,
    org_time: 1970-01-01T00:00:00Z,
    rec_time: 1970-01-01T00:00:00Z,
    xmt_time: 2018-03-24T17:27:05.506634Z,
    num_exts: 0
} (1)
{
    _path: "ntp",
    ts: 2018-03-24T17:27:04.16334Z,
    uid: "CiWD2E4B4MdjDfbRJf",
    id: {
        orig_h: 10.47.4.100,
        orig_p: 123,
        resp_h: 162.210.111.4,
        resp_p: 123
    },
    version: 4,
    mode: 3,
    stratum: 2,
    poll: 17m4s,
    precision: 0s,
    root_delay: 155.029ms,
    root_disp: 340.332ms,
    ref_id: "131.188.3.221",
    ref_time: 2018-03-24T01:46:11.275708Z,
    org_time: 1970-01-01T00:00:00Z,
    rec_time: 1970-01-01T00:00:00Z,
    xmt_time: 2018-03-24T17:27:05.506634Z,
    num_exts: 0
} (1)
{
    _path: "ntp",
    ts: 2018-03-24T17:27:05.117271Z,
    uid: "CAz1Il4rpcT0hDwUTb",
    id: {
        orig_h: 10.47.8.30,
        orig_p: 42093,
        resp_h: 45.127.113.2,
        resp_p: 123
    },
    version: 4,
    mode: 3,
    stratum: 0,
    poll: 17m4s,
    precision: 1193046h23m20s,
    root_delay: 0s,
    root_disp: 0s,
    ref_id: "\x00\x00\x00\x00",
    ref_time: 1970-01-01T00:00:00Z,
    org_time: 1970-01-01T00:00:00Z,
    rec_time: 1970-01-01T00:00:00Z,
    xmt_time: 1902-03-31T17:46:41.751199Z,
    num_exts: 0
} (1)
{
    _path: "ntp",
    ts: 2018-03-24T17:27:05.117275Z,
    uid: "CAz1Il4rpcT0hDwUTb",
    id: {
        orig_h: 10.47.8.30,
        orig_p: 42093,
        resp_h: 45.127.113.2,
        resp_p: 123
    },
    version: 4,
    mode: 3,
    stratum: 0,
    poll: 17m4s,
    precision: 1193046h23m20s,
    root_delay: 0s,
    root_disp: 0s,
    ref_id: "\x00\x00\x00\x00",
    ref_time: 1970-01-01T00:00:00Z,
    org_time: 1970-01-01T00:00:00Z,
    rec_time: 1970-01-01T00:00:00Z,
    xmt_time: 1902-03-31T17:46:41.751199Z,
    num_exts: 0
} (1)
{
    _path: "ntp",
    ts: 2018-03-24T17:27:06.977611Z,
    uid: "CXDiZC3PMj3wLnEUHe",
    id: {
        orig_h: 10.47.7.100,
        orig_p: 123,
        resp_h: 45.127.112.2,
        resp_p: 123
    },
    version: 4,
    mode: 3,
    stratum: 3,
    poll: 17m4s,
    precision: 0s,
    root_delay: 29.266ms,
    root_disp: 795.074ms,
    ref_id: "129.250.35.250",
    ref_time: 2018-03-24T01:50:11.759847Z,
    org_time: 2018-03-24T01:50:57.667271Z,
    rec_time: 2018-03-24T01:50:57.697887Z,
    xmt_time: 2018-03-24T17:27:06.289964Z,
    num_exts: 0
} (1)
{
    _path: "ntp",
    ts: 2018-03-24T17:27:06.977613Z,
    uid: "CXDiZC3PMj3wLnEUHe",
    id: {
        orig_h: 10.47.7.100,
        orig_p: 123,
        resp_h: 45.127.112.2,
        resp_p: 123
    },
    version: 4,
    mode: 3,
    stratum: 3,
    poll: 17m4s,
    precision: 0s,
    root_delay: 29.266ms,
    root_disp: 795.074ms,
    ref_id: "129.250.35.250",
    ref_time: 2018-03-24T01:50:11.759847Z,
    org_time: 2018-03-24T01:50:57.667271Z,
    rec_time: 2018-03-24T01:50:57.697887Z,
    xmt_time: 2018-03-24T17:27:06.289964Z,
    num_exts: 0
} (1)
{
    _path: "ntp",
    ts: 2018-03-24T17:27:07.977684Z,
    uid: "CjJCFEhfWLBzqQrWb",
    id: {
        orig_h: 10.47.7.100,
        orig_p: 123,
        resp_h: 129.250.35.250,
        resp_p: 123
    },
    version: 4,
    mode: 3,
    stratum: 3,
    poll: 17m4s,
    precision: 0s,
    root_delay: 29.266ms,
    root_disp: 795.09ms,
    ref_id: "129.250.35.250",
    ref_time: 2018-03-24T01:50:11.759847Z,
    org_time: 2018-03-24T01:50:12.638332Z,
    rec_time: 2018-03-24T01:50:12.639196Z,
    xmt_time: 2018-03-24T17:27:07.29003Z,
    num_exts: 0
} (1)
{
    _path: "ntp",
    ts: 2018-03-24T17:27:07.977686Z,
    uid: "CjJCFEhfWLBzqQrWb",
    id: {
        orig_h: 10.47.7.100,
        orig_p: 123,
        resp_h: 129.250.35.250,
        resp_p: 123
    },
    version: 4,
    mode: 3,
    stratum: 3,
    poll: 17m4s,
    precision: 0s,
    root_delay: 29.266ms,
    root_disp: 795.09ms,
    ref_id: "129.250.35.250",
    ref_time: 2018-03-24T01:50:11.759847Z,
    org_time: 2018-03-24T01:50:12.638332Z,
    rec_time: 2018-03-24T01:50:12.639196Z,
    xmt_time: 2018-03-24T17:27:07.29003Z,
    num_exts: 0
} (1)
```

### PR DESCRIPTION
**Pull request by mccanne**
The logic to scan zson primitive values did not properly handle the
recent changes to read input as a stream and had presumed all of
the needed input was in the cursor.  This commit fixes peekPrimitive()
to make sure there is data up to the next whitespace, comma, or EOF
(since none of this can appear in a primitive value).

I would spend a bit more time here to do a bit more review and more 
comprehensive tests at this point, but there are other priorities so I 
created issue #2057 

Fixes #2056

### CODE REVIEW

File: zson/lexer.go [hunk 1]
```diff
@@ -343,6 +343,32 @@ func (l *Lexer) scanIdentifier() (string, error) {
...
 func (l *Lexer) peekPrimitive() (string, error) {
+	var err error
+	var off int
+	for {
+		if off+utf8.UTFMax > len(l.cursor) {
+			err = l.check(off + utf8.UTFMax)
+			if off <= len(l.cursor) || err != nil {
+				break
+			}
+		}
```
Comment (nwt) [inline zson/lexer.go:360]: If the purpose of this statement is to ensure that `l.cursor[off:]`contains at least `utf8.UTFMax` bytes, then it seems like something simpler should suffice.
```suggestion
		err = l.check(off + utf8.UTFMax)
		if err != nil {
			break
		}
```

**Review by nwt — APPROVED** [review]
