### PR TITLE
Fix lost warnings in log/path endpoint

### LINKED ISSUE #1901: zqd /log/path endpoint drops warnings
(I ran into while working on #1895)

Given this input file with a bad line:
```
$ cat bad.tzng
#0:record[ip:string]
0:[1.1.1.1;]
0:[1.1.1.2;
```

The `/log` enpoint produces a warning for the bad line
```
$ zapi -s test post -f in-bad.tzng
warning: file:///Users/henridf/work/brim/zq/in-bad.tzng: line 3: tzng syntax error: unterminated container
posted 46B in 1.096294ms
```

But the `/log/path` endpoint does not:

```
$ zapi -s test postpath -f in-bad.tzng
100.0% 46B/46B
posted 46B in 1.204216ms
```

### PR DESCRIPTION
**Pull request by henridf**
close #1901 (and sets things up for #1895 )

### CODE REVIEW

File: ppl/zqd/ingest/log.go [hunk 1]
```diff
@@ -91,7 +92,13 @@ func NewLogOp(ctx context.Context, store storage.Storage, req api.LogPostRequest
 }
 
 func (p *LogOp) Warn(msg string) error {
-	p.warnings = append(p.warnings, msg)
+	// warnings received before we've started our goroutine are
+	// saved here and will be drained in start()
+	if p.warnings != nil {
+		p.warnings = append(p.warnings, msg)
```
Comment (marktwallace) [inline ppl/zqd/ingest/log.go:98]: I'm not clear on whether this could ever be called from a goroutine, but if it is, then writing to the channel will be thread-safe, but the append will not be thread-safe without a lock.

**Review by marktwallace — APPROVED** [review]
This looks fine as long as the same LogOp instance is never used in more than one goroutine.

File: ppl/zqd/ingest/log.go (hunk 1 above)
Comment (henridf) [reply ppl/zqd/ingest/log.go:98]: Yes, the only goroutine that calls Warn is the one started by NewLogOp (`go p.start(ctx, store)`). This is pre-existing behavior. I'll add a comment to clarify.

**Comment by philrz** [comment]
Also fixes #1895.
