### PR TITLE
space config: Fix v0 duplicate name migrations

### LINKED ISSUE #1111: Extra characters in Space names after upgrade to v0.15.0
Discovered while doing a smoke test on the Brim release candidate tagged `v0.15.0`.

I had Spaces that had been created when running `v0.14.0` named "hello.pcapng.brim" and "wrccdc.pcap.brim", created by importing pcaps. After the upgrade, the Space names visible in the app had extra characters visible in them.

image

### PR DESCRIPTION
**Pull request by mattnibs**
When migrating from config v0 to v1 only create unique name if
names in space have a collision.

Also:
- Add check in writeConfig to ensure the saved config file has an
update-to-date Version number.
- Add mananger test that a new space has an update-to-date Version
number.

Closes #1111

### CODE REVIEW

File: zqd/space/config.go [hunk 1]
```diff
@@ -175,6 +171,9 @@ func migrateConfigV2(data []byte, _ iosrc.URI) (int, []byte, error) {
 }
 
 func writeConfig(spaceURI iosrc.URI, c config) error {
+	if c.Version != configVersion {
+		return fmt.Errorf("writing an out of date config, expected version %d got %d", configVersion, c.Version)
```
Comment (nwt) [inline zqd/space/config.go:175]:
```suggestion
		return fmt.Errorf("writing an out of date config: expected version %d, got %d", configVersion, c.Version)
```
