### PR TITLE
archivestore: Delay before purge

### LINKED ISSUE #1960: zqd archive error: metadata for file not found
This test failure was seen on the `eks-test-zapi-1`ci  job for the postgres helm pr: https://github.com/brimsec/zq/pull/1948

Given that zqd successfully connects with postgres, this appears unrelated to the feature work in the pr.

Test Logs:

```
zapi -s files get -workers 2 -t '"FgzbkQ15TOoOENn1lb" | sort tx_hosts'
0:[files;1521940131.094903;FgzbkQ15TOoOENn1lb;[198.199.95.203;][10.47.25.80;][Cc4q8L1Hhp9MjJiVcl;]SSL;0;[MD5;SHA1;X509;SHA256;]application/x-x509-ca-cert;-;0;-;F;1174;-;0;0;F;-;b15409274f54ad8f023d3b85a5ecec5d;e6a3b45b062d509b3382282d196efe97d5956ccb;25847d668eb4f04fdd40b12b6b0740c567da7d024308eb6c2c96fe41d9de218d;-;-;-;]
Handling connection for 9867
status code 400: invalid worker op request: failed to read chunk metadata from s3://zq-ci-test/21-01-12.342/zd/20180323/m-1myPUtlCc6vWqxJBlJKTA2qRfEy.zng: item does not exist
```

Action url: https://github.com/brimsec/zq/pull/1948/checks?check_run_id=1688778486

### PR DESCRIPTION
**Pull request by mattnibs**
When running a compaction on an archivestore, after the Compact phase is
complete, add a one minute delay before a Purge run. This
is meant as a stop-gap solution for the bug encountered in #1960.

Closes #1960

### CODE REVIEW

File: ppl/zqd/storage/archivestore/archivestore.go [hunk 1]
```diff
@@ -157,5 +158,16 @@ func (s *Storage) Compact(ctx context.Context, logger *zap.Logger) error {
...
 	}
-	return archive.Purge(ctx, s.ark, logger)
+	select {
+	case <-ctx.Done():
+		return ctx.Err()
+	// Wait for one minute before doing purge. This delay is here to prevent
+	// the case where a directory listing of chunks is made for search, the tsdir is
+	// compacted and purged, then the search attempts to read a deleted chunk from
+	// its now stale directory listing.
+	// This is a stop-gap solution to this problem; a more robust solution
```
Comment (nwt) [inline ppl/zqd/storage/archivestore/archivestore.go:168]:
```suggestion
	// This is a stopgap solution to this problem; a more robust solution
```

**Review by nwt — APPROVED** [review]

**Review by alfred-landrum — APPROVED** [review]
I filed #1985 to track work for a longer term solution.
