### PR TITLE
lake.Index.Find: Return all matched records

### LINKED ISSUE #2241: "zar find" on custom index returning incomplete results (regression at 53eed63)
Consider the following aggregations run against the [zq-sample-data](https://github.com/brimsec/zq-sample-data):

```
$ zq -f table 'id.orig_h=10.164.94.120 | count() by _path, id.orig_h | count=sum(count) by _path | sort -r count,_path' work/zq-sample-data/zeek-default/*
_PATH       COUNT
conn        26726
http        13485
ssl         9538
rdp         4116
smtp        1178
weird       316
ftp         93
ntlm        80
smb_mapping 65
notice      35
dpd         24
dns         8
rfb         3
dce_rpc     2
ssh         1
smb_files   1
```

The [`zar` README](https://github.com/brimsec/zq/blob/master/ppl/cmd/zar/README.md) has an example that gets to the same result using a custom index, which was working as of `zq` commit `9f71a5d`. I've adjusted it slightly here for clarity.

```
$ zar -version
Version: v0.25.0-16-g9f71a5d1

$ rm -rf $ZAR_ROOT && \
  zq work/zq-sample-data/zeek-default/*.gz | zar import -s 25MB - && \
  zar index -q -o custom.zng -k id.orig_h -z "count() by _path, id.orig_h | sort id.orig_h" && \
  zar find -z -x custom.zng 10.164.94.120 | zq -f table "count=sum(count) by _path | sort -r count,_path" -

_PATH       COUNT
conn        26726
http        13485
ssl         9538
rdp         4116
smtp        1178
weird       316
ftp         93
ntlm        80
smb_mapping 65
notice      35
dpd         24
dns         8
rfb         3
dce_rpc     2
ssh         1
smb_files   1
```

However, if I advance to the next commit `53eed63` (associated with #1745, cc: @mattnibs), now I get an incomplete/inconsistent result.

```
$ zq -version
Version: v0.25.0-17-g53eed630

$ rm -rf $ZAR_ROOT && \
  zq work/zq-sample-data/zeek-default/*.gz | zar import -s 25MB - && \
  zar index -q -o custom.zng -k id.orig_h -z "count() by _path, id.orig_h | sort id.orig_h" && \
  zar find -z -x custom.zng 10.164.94.120 | zq -f table "count=sum(count) by _path | sort -r count,_path" -

_PATH COUNT
http  2766
ssl   168
dpd   18
dns   6

$ rm -rf $ZAR_ROOT && \
  zq work/zq-sample-data/zeek-default/*.gz | zar import -s 25MB - && \
  zar index -q -o custom.zng -k id.orig_h -z "count() by _path, id.orig_h | sort id.orig_h" && \
  zar find -z -x custom.zng 10.164.94.120 | zq -f table "count=sum(count) by _path | sort -r count,_path" -

_PATH COUNT
conn  207
ftp   28
smtp  8
rfb   1
```

This problem remains with us in current commits as well, such as `5cd41763`. To make this work I have to add `create` to the `zar index` command, and the `zar find -z` now means to output ZSON instead of ZNG, but functionally it lands us in the same place.

```
$ zq -version
Version: v0.29.0-71-g5cd41763

$ rm -rf $ZAR_ROOT && \
  zq work/zq-sample-data/zeek-default/*.gz | zar import -s 25MB - && \
  zar index create -q -o custom.zng -k id.orig_h -z "count() by _path, id.orig_h | sort id.orig_h" && \
  zar find -z -x custom.zng 10.164.94.120 | zq -f table "count=sum(count) by _path | sort -r count,_path" -

_PATH       COUNT
conn        207
ssl         168
ftp         28
smb_mapping 12
```

### PR DESCRIPTION
**Pull request by mattnibs**
Have lake.Index.Find return a zbuf.ReadCloser that reads all records in
a microindex matching a query, not just the first hit.

Closes #2241

### CODE REVIEW

File: microindex/finder.go [hunk 1]
```diff
@@ -166,34 +166,31 @@ func (f *Finder) Lookup(keys *zng.Record) (*zng.Record, error) {
 	return lookup(reader, compare, f.trailer.Order, eql)
 }
 
-func (f *Finder) LookupAll(ctx context.Context, hits chan<- *zng.Record, keys *zng.Record) error {
```
[the remark this answers is not in the document]
Comment (mattnibs) [reply microindex/finder.go]: @alfred-landrum after looking at the code for Finder I realized that it didn't make sense to have this return a zbuf.Reader since it would be confusing that the parent Finder would need to be closed once the Reader has been read through. As such I decided to keep the signature the same for Finder.LookupAll and added a separate FinderReader struct (implementing zbuf.ReadCloser) that can be used if one wants to stream results from a microindex search. @nwt had the idea that `LookupAll` could accept a zbuf.Writer, perhaps we'll want to change it to do this at some point.

File: microindex/findreader.go [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+	finder  *Finder
+	reader  zbuf.Reader
+}
+
+func NewFinderReader(ctx context.Context, zctx *resolver.Context, uri iosrc.URI, inputs ...string) (*FinderReader, error) {
+	finder, err := NewFinder(ctx, zctx, uri)
+	if err != nil {
+		return nil, err
+	}
+	keys, err := finder.ParseKeys(inputs...)
```
Comment (alfred-landrum) [inline microindex/findreader.go:26]: Do the error cases below here need to call `finder.Close()`?

**Review by alfred-landrum — COMMENTED** [review]
The new FinderReader approach is 👍 .

File: microindex/findreader.go (hunk 2 above)
Comment (mattnibs) [reply microindex/findreader.go:26]: Good point!

File: ppl/lake/finder.go [hunk 3]
```diff
@@ -102,25 +102,31 @@ func Find(ctx context.Context, zctx *resolver.Context, lk *Lake, query index.Que
...
 			// says it's ok.  Otherwise, we return ErrNotExist since
 			// the client was looking for something that wasn't indexed,
 			// and they would probably want to know.
 			return nil
 		}
 
-		if rec, err = opt.addPath(lk, chunk, rec); err != nil {
-			return err
-		}
+		defer reader.Close()
```
Comment (alfred-landrum) [inline ppl/lake/finder.go:114]: The error handling needs adjustment here, unrelated to these changes.  There's a missing `if err != nil return` that should happen before this line, I think.

Comment (mattnibs) [reply ppl/lake/finder.go:114]: Right you are.

**Review by alfred-landrum — APPROVED** [review]
